const PROJECT_CONTROL_BASE_URL = 'https://localhost:44373/api/';

const SEARCH_EMPLOYEE_ENDPOINT = PROJECT_CONTROL_BASE_URL + 'employee/SearchEmployees';
const GET_ALL_EMPLOYEES_ENDPOINT = PROJECT_CONTROL_BASE_URL + 'employee/Employees';

const GET_PROJECT_BY_NAME_ENDPOINT  = PROJECT_CONTROL_BASE_URL + 'project/GetProjectByName';
const GET_ALL_PROJECTS_ENDPOINT = PROJECT_CONTROL_BASE_URL + 'project/GetAllProjects';

const ADD_NEW_CLIENT = PROJECT_CONTROL_BASE_URL + 'contract/AddNewClient';

const GET_ALL_EMPLOYEE_CONTRACTS = PROJECT_CONTROL_BASE_URL + 'Contract/EmployeeContract/GetAllActiveEmployeeContracts';
const GET_ALL_CLIENT_CONTRACTS = PROJECT_CONTROL_BASE_URL + 'Contract/ClientContracts';

const ADD_NEW_PROJECT = PROJECT_CONTROL_BASE_URL + 'Project/AddNewProject';

const GET_ALL_CLIENTS = PROJECT_CONTROL_BASE_URL + 'Client/GetAllClients';


export default {
  SEARCH_EMPLOYEE_ENDPOINT,
  GET_ALL_EMPLOYEES_ENDPOINT,
  GET_PROJECT_BY_NAME_ENDPOINT,
  GET_ALL_PROJECTS_ENDPOINT,
  ADD_NEW_CLIENT,
  GET_ALL_CLIENT_CONTRACTS,
  GET_ALL_EMPLOYEE_CONTRACTS,
  ADD_NEW_PROJECT,
  GET_ALL_CLIENTS
}